# Generated by Django 4.2.7 on 2023-12-03 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=150)),
                ('Apellido', models.CharField(max_length=150)),
                ('Usuario', models.CharField(max_length=10)),
                ('Clave', models.CharField(max_length=50)),
                ('Correo', models.CharField(max_length=150)),
            ],
        ),
    ]
